// Rough Cut — sample review content

const REVIEWS = [
  {
    slug: 'ember-hollow',
    title: 'Ember Hollow',
    dev: 'Two-Person Fire Team',
    platform: 'PC · Steam Deck',
    hours: 14,
    date: 'APR 16, 2026',
    author: 'Mara Vance',
    tags: ['roguelite', 'deckbuilder', 'pixel'],
    verdict: 'HIDDEN GEM',
    hook: 'A deckbuilder that actually respects your time and your spleen.',
    lede: 'Most roguelite deckbuilders want you to suffer for 300 hours before they respect you. Ember Hollow gets it done in twenty. That\'s not a weakness — that\'s a feature.',
    pullquote: 'The kind of game that ruins your sleep schedule on a Tuesday.',
    body: [
      'Let\'s get the obvious out of the way: yes, it looks like every pixel-art indie game you scrolled past during the last six Steam Next Fests. No, that does not matter. Ember Hollow is the rare entry in a bloated genre that knows exactly what it wants to be and says no to everything else.',
      'The hook is compression. A run is forty minutes tops. The deck caps at fifteen cards. Every fight matters because there is no fat to burn through. It\'s a roguelite with the confidence to stop.',
      'The meta-progression is where the developers earn their keep. Instead of a sprawling unlock tree that drip-feeds you excitement, you get four characters and each one fundamentally rewires how combat works. The Hound trades initiative for burn-over-time. The Monk cannot attack — only reflect. It is, delightfully, a pain.',
      'Is it perfect? Absolutely not. The boss rotation gets predictable by your fifth win. The soundtrack is four tracks, two of which you will grow to resent. The story — if you can call it that — is delivered by a narrator who sounds like a distressed audiobook app.',
      'But this is a rough cut review blog, and Ember Hollow is a rough gem. Go play it. Tell your friends. Refuse to recommend a fourth roguelite this month because this is the only one you owe anyone.',
    ],
    pros: ['Fights that end before you get bored', 'Four builds that feel genuinely different', 'Runs on a potato'],
    cons: ['Boss rotation thins out fast', 'Soundtrack needs more tracks', 'Narrator sounds like he\'s being held hostage'],
  },
  {
    slug: 'neon-dispatch',
    title: 'Neon Dispatch',
    dev: 'Orbit&Knife',
    platform: 'PC · Switch',
    hours: 9,
    date: 'APR 12, 2026',
    author: 'T. Okonkwo',
    tags: ['narrative', 'sim', 'cyberpunk'],
    verdict: 'BANGER',
    hook: 'You are a 2099 taxi dispatcher. Somehow this is the most stressful game of the year.',
    lede: 'Neon Dispatch is a game about coordinating the ride-shares of the terminally online in a collapsing city-state. Reader: it is incredible.',
    pullquote: 'Spreadsheet horror with style to burn.',
  },
  {
    slug: 'salt-rot',
    title: 'Salt & Rot',
    dev: 'Bad Weather Club',
    platform: 'PC',
    hours: 22,
    date: 'APR 09, 2026',
    author: 'Jas Petrov',
    tags: ['survival', 'horror', 'coastal'],
    verdict: 'ROUGH',
    hook: 'Promising atmosphere drowned in a menu system designed by a war criminal.',
    lede: 'Salt & Rot has the bones of a cult classic and the UI of a 1998 DMV kiosk. Guess which one you\'ll spend more time fighting.',
  },
  {
    slug: 'vellum-songs',
    title: 'The Vellum Songs',
    dev: 'Marguerite Solo',
    platform: 'PC · Mac',
    hours: 6,
    date: 'APR 05, 2026',
    author: 'Mara Vance',
    tags: ['narrative', 'music', 'watercolor'],
    verdict: 'HIDDEN GEM',
    hook: 'Six hours. One developer. Will make you call your mom.',
    lede: 'A hand-painted narrative adventure about recovering your grandmother\'s song archive. It cost one person three years and will cost you a box of tissues.',
  },
  {
    slug: 'concrete-mile',
    title: 'Concrete Mile',
    dev: 'Garage Studio North',
    platform: 'PC · PS5',
    hours: 17,
    date: 'APR 02, 2026',
    author: 'D. Whitfield',
    tags: ['racing', 'physics', 'brutalist'],
    verdict: 'CULT CLASSIC',
    hook: 'A racing game set entirely in parking garages. I cannot explain why it rips.',
    lede: 'Every track is a municipal parking structure. The physics are barely legal. And somehow this is the best racing game since Trackmania.',
  },
  {
    slug: 'pastoral-protocol',
    title: 'Pastoral Protocol',
    dev: 'Hollowpine',
    platform: 'PC',
    hours: 3,
    date: 'MAR 28, 2026',
    author: 'T. Okonkwo',
    tags: ['farming', 'cozy', 'horror'],
    verdict: 'WAIT & SEE',
    hook: 'Early access cozy-farm-that-is-secretly-a-horror-game. Jury\'s out.',
    lede: 'Promising premise. Rough edges. Come back in six months. Until then: proceed with caution and a save backup.',
  },
  {
    slug: 'iron-penitent',
    title: 'The Iron Penitent',
    dev: 'Basilisk Forge',
    platform: 'PC',
    hours: 31,
    date: 'MAR 22, 2026',
    author: 'Jas Petrov',
    tags: ['souls-like', 'metroidvania'],
    verdict: 'SKIP IT',
    hook: 'The eighteenth souls-metroidvania this quarter. Guess what — it\'s also the worst.',
    lede: 'There is a version of this game where the combat ideas would sing. That version would have needed a publisher, a producer, and someone willing to say no.',
  },
  {
    slug: 'lowtide',
    title: 'Lowtide',
    dev: 'Ginger & Salt',
    platform: 'PC · Mobile',
    hours: 4,
    date: 'MAR 18, 2026',
    author: 'Mara Vance',
    tags: ['puzzle', 'zen', 'tidal'],
    verdict: 'BANGER',
    hook: 'A puzzle game that moves at the speed of actual tides. Somehow: thrilling.',
    lede: 'Lowtide runs on a real-world tidal clock. Yes, really. And it works.',
  },
];

Object.assign(window, { REVIEWS });
